# Logistic Regression

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
%matplotlib inline

## Importing the dataset

In [2]:
dataset = pd.read_csv('loan_data.csv')
X = dataset.iloc[:, 2:-1].values
y = dataset.iloc[:, -1].values

In [3]:
dataset.head()

credit.policy             purpose  int.rate  installment  log.annual.inc  \
0              1  debt_consolidation    0.1189       829.10       11.350407   
1              1         credit_card    0.1071       228.22       11.082143   
2              1  debt_consolidation    0.1357       366.86       10.373491   
3              1  debt_consolidation    0.1008       162.34       11.350407   
4              1         credit_card    0.1426       102.92       11.299732   

     dti  fico  days.with.cr.line  revol.bal  revol.util  inq.last.6mths  \
0  19.48   737        5639.958333      28854        52.1               0   
1  14.29   707        2760.000000      33623        76.7               0   
2  11.63   682        4710.000000       3511        25.6               1   
3   8.10   712        2699.958333      33667        73.2               1   
4  14.97   667        4066.000000       4740        39.5               0   

   delinq.2yrs  pub.rec  not.fully.paid  
0            0        0               0  
1            0        0               0  
2            0        0               0  
3            0        0               0  
4            1        0               0

In [4]:
print(X)

[[1.18900000e-01 8.29100000e+02 1.13504065e+01 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [1.07100000e-01 2.28220000e+02 1.10821426e+01 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [1.35700000e-01 3.66860000e+02 1.03734912e+01 ... 1.00000000e+00
  0.00000000e+00 0.00000000e+00]
 ...
 [1.07100000e-01 9.78100000e+01 1.05966347e+01 ... 8.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [1.60000000e-01 3.51580000e+02 1.08197783e+01 ... 5.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [1.39200000e-01 8.53430000e+02 1.12644641e+01 ... 6.00000000e+00
  0.00000000e+00 0.00000000e+00]]


In [5]:
print(y)

[0 0 0 ... 1 1 1]


## Splitting the dataset into the Training set and Test set

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

## Feature Scaling

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Training the Logistic Regression model on the Training set

In [8]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

## Make a Prediction 

In [9]:
y_pred = classifier.predict(X_test)

In [10]:
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [11]:
df=pd.DataFrame(y_test, y_pred)
df

0
0   0
0   0
0   0
0   0
1   0
.. ..
0   0
0   0
0   0
0   0
0   1

[2395 rows x 1 columns]

## Making the Confusion Matrix

In [12]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

print('confusion_matrix: ','\n',confusion_matrix(y_test, y_pred))
print ('\n')
print('classification_report: ','\n',classification_report(y_test, y_pred))
print ('\n')
print('accuracy_score: ','\n',accuracy_score(y_test, y_pred))


confusion_matrix:  
 [[2004   10]
 [ 376    5]]


classification_report:  
               precision    recall  f1-score   support

           0       0.84      1.00      0.91      2014
           1       0.33      0.01      0.03       381

    accuracy                           0.84      2395
   macro avg       0.59      0.50      0.47      2395
weighted avg       0.76      0.84      0.77      2395



accuracy_score:  
 0.838830897703549


## Applying k-Fold Cross Validation

In [13]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 83.96 %
Standard Deviation: 0.28 %
